/**
 * Glossary data for Free/Pro translation.
 *  - GLOSSARY: core fintech/finance terms per language.
 *  - COURSE_GLOSSARY: crypto-course terms per language.
 *  - LANG_NAMES: display names used in the OpenAI prompt.
 * Inlined into dist/ui.html at build time (esbuild, globalName FintechData).
 */
export const GLOSSARY = {
  es: {
    // Core finance
    "APR":"TAE","Annual Percentage Rate":"Tasa Anual Equivalente",
    "interest rate":"tasa de interés","annual returns":"rendimientos anuales",
    "monthly payouts":"pagos mensuales","monthly payments":"pagos mensuales",
    "balance":"saldo","statement":"extracto","account":"cuenta",
    "deposit":"depósito","withdrawal":"retiro","wire transfer":"transferencia bancaria",
    "transaction":"transacción","payment":"pago","invoice":"factura",
    "fee":"comisión","no hidden fees":"sin comisiones ocultas",
    // P2P / Crowdlending (Maclear)
    "P2P lending":"préstamos P2P","crowdlending":"crowdlending",
    "crowdfunding":"financiación colectiva","lending platform":"plataforma de préstamos",
    "investment platform":"plataforma de inversión",
    "investor":"inversor","investors":"inversores",
    "borrower":"prestatario","lender":"prestamista",
    "loan":"préstamo","loan period":"plazo del préstamo","loan term":"plazo del préstamo",
    "loan originator":"originador de préstamos",
    "funded":"financiado","repaid":"reembolsado",
    "default":"impago","late loans":"préstamos con retraso",
    "cash drag":"capital inactivo",
    "primary market":"mercado primario","secondary market":"mercado secundario",
    "total funded":"total financiado","total interest paid":"total de intereses pagados",
    "available funds":"fondos disponibles","invested funds":"fondos invertidos",
    "total funds":"fondos totales",
    // Investment
    "initial investment":"inversión inicial","investment period":"período de inversión",
    "future value":"valor futuro","earned return":"rendimiento obtenido",
    "average annual return":"rendimiento medio anual",
    "portfolio":"cartera","passive income":"ingresos pasivos",
    "principal repayment":"devolución del capital",
    "interest payment":"pago de intereses",
    "installment":"cuota","recurring payment":"pago recurrente",
    // Compliance & process
    "due diligence":"diligencia debida","risk assessment":"evaluación de riesgos",
    "risk scoring":"puntuación de riesgo","AML":"AML",
    "compliance":"cumplimiento normativo","regulated":"regulado",
    "verification":"verificación","KYC":"KYC",
    // Bonuses & rewards
    "referral bonus":"bono de referido","loyalty bonus":"bono de fidelidad",
    "welcome bonus":"bono de bienvenida","investment reward":"recompensa de inversión",
    "invite friends":"invitar amigos",
    // UI actions
    "sign up":"registrarse","log in":"iniciar sesión","register":"registrarse",
    "invest now":"invertir ahora","start investing":"empezar a invertir",
    "dashboard":"panel de control","onboarding":"alta de cliente",
    // General finance
    "collateral":"garantía","mortgage":"hipoteca","savings":"ahorros",
    "credit score":"puntuación crediticia","overdraft":"sobregiro",
    "chargeback":"contracargo","settlement":"liquidación",
    "direct debit":"domiciliación bancaria","exchange rate":"tipo de cambio",
    "payee":"beneficiario","payer":"pagador","beneficiary":"beneficiario",
    "equity":"capital","liability":"pasivo","asset":"activo",
    "dividend":"dividendo","spending limit":"límite de gasto",
    // Crypto / Web3 (Maclear Crypto Course)
    "blockchain":"blockchain","token":"token","tokens":"tokens",
    "stablecoin":"stablecoin","stablecoins":"stablecoins",
    "cryptocurrency":"criptomoneda","crypto":"cripto",
    "crypto wallet":"monedero cripto","wallet":"monedero",
    "seed phrase":"frase semilla","private key":"clave privada",
    "public address":"dirección pública","smart contract":"contrato inteligente",
    "network fees":"comisiones de red","gas fees":"tarifas de gas",
    "custodial":"custodiado","non-custodial":"no custodiado",
    "custodial wallet":"monedero custodiado",
    "non-custodial wallet":"monedero auto-custodiado",
    "fiat":"moneda fiduciaria","pegged":"vinculado",
    "decentralized":"descentralizado","centralized":"centralizado",
    "capital provider":"proveedor de capital",
    "repayment schedule":"calendario de pagos",
    "leverage":"apalancamiento","diversification":"diversificación",
    "yield":"rendimiento","returns":"rendimientos",
    "liquidity":"liquidez","protocol":"protocolo",
    "staking":"staking","airdrop":"airdrop",
    "mining":"minería","validator":"validador",
    "consensus":"consenso","bridge":"puente",
    "on-chain":"on-chain","off-chain":"off-chain",
    "scam":"estafa","phishing":"phishing",
    "Learn & Earn":"Aprende y Gana",
    "start learning":"empezar a aprender",
    "checklist":"lista de verificación",
    "step-by-step":"paso a paso",
    "beginner":"principiante","beginners":"principiantes",
    // Tech terms — must stay untranslated
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","DEX":"DEX","CEX":"CEX","DApp":"DApp",
    "Layer 1":"Layer 1","Layer 2":"Layer 2",
    // Date/era labels — keep verbatim
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    // Infographic card text — concise translations
    "Evolution of the Web from 1.0 to 3.0":"Evolución de la Web del 1.0 al 3.0",
    "Static read-only web pages":"Páginas web estáticas de solo lectura",
    "Information-centric and interactive":"Centrada en la información e interactiva",
    "User-centric, decentralized, private and secure":"Centrada en el usuario, descentralizada, privada y segura",
    "read-only":"solo lectura","user-centric":"centrada en el usuario",
    "private and secure":"privada y segura"
  },
  it: {
    "APR":"TAEG","Annual Percentage Rate":"Tasso Annuo Effettivo Globale",
    "interest rate":"tasso di interesse","annual returns":"rendimenti annuali",
    "monthly payouts":"pagamenti mensili","monthly payments":"pagamenti mensili",
    "balance":"saldo","statement":"estratto conto","account":"conto",
    "deposit":"deposito","withdrawal":"prelievo","wire transfer":"bonifico bancario",
    "transaction":"transazione","payment":"pagamento","invoice":"fattura",
    "fee":"commissione","no hidden fees":"nessuna commissione nascosta",
    "P2P lending":"prestiti P2P","crowdlending":"crowdlending",
    "crowdfunding":"crowdfunding","lending platform":"piattaforma di prestiti",
    "investment platform":"piattaforma di investimento",
    "investor":"investitore","investors":"investitori",
    "borrower":"mutuatario","lender":"prestatore",
    "loan":"prestito","loan period":"durata del prestito","loan term":"durata del prestito",
    "loan originator":"originatore di prestiti",
    "funded":"finanziato","repaid":"rimborsato",
    "default":"insolvenza","late loans":"prestiti in ritardo",
    "cash drag":"capitale inattivo",
    "primary market":"mercato primario","secondary market":"mercato secondario",
    "total funded":"totale finanziato","total interest paid":"totale interessi pagati",
    "available funds":"fondi disponibili","invested funds":"fondi investiti",
    "total funds":"fondi totali",
    "initial investment":"investimento iniziale","investment period":"periodo di investimento",
    "future value":"valore futuro","earned return":"rendimento ottenuto",
    "average annual return":"rendimento medio annuo",
    "portfolio":"portafoglio","passive income":"reddito passivo",
    "principal repayment":"rimborso del capitale",
    "interest payment":"pagamento degli interessi",
    "installment":"rata","recurring payment":"pagamento ricorrente",
    "due diligence":"due diligence","risk assessment":"valutazione del rischio",
    "risk scoring":"punteggio di rischio","AML":"AML",
    "compliance":"conformità normativa","regulated":"regolamentato",
    "verification":"verifica","KYC":"KYC",
    "referral bonus":"bonus referral","loyalty bonus":"bonus fedeltà",
    "welcome bonus":"bonus di benvenuto","investment reward":"premio di investimento",
    "invite friends":"invita amici",
    "sign up":"registrati","log in":"accedi","register":"registrati",
    "invest now":"investi ora","start investing":"inizia a investire",
    "dashboard":"pannello di controllo","onboarding":"registrazione cliente",
    "collateral":"garanzia","mortgage":"mutuo","savings":"risparmi",
    "credit score":"punteggio di credito","overdraft":"scoperto",
    "chargeback":"storno","settlement":"regolamento",
    "direct debit":"addebito diretto","exchange rate":"tasso di cambio",
    "payee":"beneficiario","payer":"pagatore","beneficiary":"beneficiario",
    "equity":"capitale","liability":"passività","asset":"attività",
    "dividend":"dividendo","spending limit":"limite di spesa",
    "blockchain":"blockchain","token":"token","tokens":"token",
    "stablecoin":"stablecoin","stablecoins":"stablecoin",
    "cryptocurrency":"criptovaluta","crypto":"cripto",
    "crypto wallet":"portafoglio crypto","wallet":"portafoglio",
    "seed phrase":"frase seed","private key":"chiave privata",
    "public address":"indirizzo pubblico","smart contract":"contratto intelligente",
    "network fees":"commissioni di rete","gas fees":"commissioni gas",
    "custodial":"custodiale","non-custodial":"non custodiale",
    "custodial wallet":"portafoglio custodiale",
    "non-custodial wallet":"portafoglio non custodiale",
    "fiat":"valuta fiat","pegged":"ancorato",
    "decentralized":"decentralizzato","centralized":"centralizzato",
    "capital provider":"fornitore di capitale",
    "repayment schedule":"piano di rimborso",
    "leverage":"leva finanziaria","diversification":"diversificazione",
    "yield":"rendimento","returns":"rendimenti",
    "liquidity":"liquidità","protocol":"protocollo",
    "staking":"staking","airdrop":"airdrop",
    "mining":"mining","validator":"validatore",
    "consensus":"consenso","bridge":"bridge",
    "on-chain":"on-chain","off-chain":"off-chain",
    "scam":"truffa","phishing":"phishing",
    "Learn & Earn":"Impara e Guadagna",
    "start learning":"inizia a imparare",
    "checklist":"checklist","step-by-step":"passo dopo passo",
    "beginner":"principiante","beginners":"principianti",
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","DEX":"DEX","CEX":"CEX","DApp":"DApp",
    "Layer 1":"Layer 1","Layer 2":"Layer 2",
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    "Evolution of the Web from 1.0 to 3.0":"Evoluzione del Web dal 1.0 al 3.0",
    "Static read-only web pages":"Pagine web statiche in sola lettura",
    "Information-centric and interactive":"Incentrato sulle informazioni e interattivo",
    "User-centric, decentralized, private and secure":"Incentrato sull'utente, decentralizzato, privato e sicuro",
    "read-only":"sola lettura","user-centric":"incentrato sull'utente"
  },
  fr: {
    "APR":"TAEG","Annual Percentage Rate":"Taux Annuel Effectif Global",
    "interest rate":"taux d'intérêt","annual returns":"rendements annuels",
    "monthly payouts":"versements mensuels","monthly payments":"paiements mensuels",
    "balance":"solde","statement":"relevé","account":"compte",
    "deposit":"dépôt","withdrawal":"retrait","wire transfer":"virement bancaire",
    "transaction":"transaction","payment":"paiement","invoice":"facture",
    "fee":"frais","no hidden fees":"aucuns frais cachés",
    "P2P lending":"prêt P2P","crowdlending":"crowdlending",
    "crowdfunding":"financement participatif","lending platform":"plateforme de prêt",
    "investment platform":"plateforme d'investissement",
    "investor":"investisseur","investors":"investisseurs",
    "borrower":"emprunteur","lender":"prêteur",
    "loan":"prêt","loan period":"durée du prêt","loan term":"durée du prêt",
    "loan originator":"originateur de prêts",
    "funded":"financé","repaid":"remboursé",
    "default":"défaut de paiement","late loans":"prêts en retard",
    "cash drag":"capital inactif",
    "primary market":"marché primaire","secondary market":"marché secondaire",
    "total funded":"total financé","total interest paid":"total des intérêts versés",
    "available funds":"fonds disponibles","invested funds":"fonds investis",
    "total funds":"fonds totaux",
    "initial investment":"investissement initial","investment period":"période d'investissement",
    "future value":"valeur future","earned return":"rendement obtenu",
    "average annual return":"rendement annuel moyen",
    "portfolio":"portefeuille","passive income":"revenu passif",
    "principal repayment":"remboursement du capital",
    "interest payment":"paiement des intérêts",
    "installment":"versement","recurring payment":"paiement récurrent",
    "due diligence":"vérification préalable","risk assessment":"évaluation des risques",
    "risk scoring":"notation du risque","AML":"LCB",
    "compliance":"conformité réglementaire","regulated":"réglementé",
    "verification":"vérification","KYC":"KYC",
    "referral bonus":"prime de parrainage","loyalty bonus":"prime de fidélité",
    "welcome bonus":"prime de bienvenue","investment reward":"récompense d'investissement",
    "invite friends":"inviter des amis",
    "sign up":"s'inscrire","log in":"se connecter","register":"s'inscrire",
    "invest now":"investir maintenant","start investing":"commencer à investir",
    "dashboard":"tableau de bord","onboarding":"inscription client",
    "collateral":"garantie","mortgage":"prêt hypothécaire","savings":"épargne",
    "credit score":"cote de crédit","overdraft":"découvert",
    "chargeback":"rétrofacturation","settlement":"règlement",
    "direct debit":"prélèvement automatique","exchange rate":"taux de change",
    "payee":"bénéficiaire","payer":"payeur","beneficiary":"bénéficiaire",
    "equity":"capitaux propres","liability":"passif","asset":"actif",
    "dividend":"dividende","spending limit":"plafond de dépenses",
    "blockchain":"blockchain","token":"jeton","tokens":"jetons",
    "stablecoin":"stablecoin","stablecoins":"stablecoins",
    "cryptocurrency":"cryptomonnaie","crypto":"crypto",
    "crypto wallet":"portefeuille crypto","wallet":"portefeuille",
    "seed phrase":"phrase de récupération","private key":"clé privée",
    "public address":"adresse publique","smart contract":"contrat intelligent",
    "network fees":"frais de réseau","gas fees":"frais de gas",
    "custodial":"custodial","non-custodial":"non-custodial",
    "custodial wallet":"portefeuille custodial",
    "non-custodial wallet":"portefeuille non-custodial",
    "fiat":"monnaie fiduciaire","pegged":"indexé",
    "decentralized":"décentralisé","centralized":"centralisé",
    "capital provider":"fournisseur de capital",
    "repayment schedule":"calendrier de remboursement",
    "leverage":"effet de levier","diversification":"diversification",
    "yield":"rendement","returns":"rendements",
    "liquidity":"liquidité","protocol":"protocole",
    "staking":"staking","airdrop":"airdrop",
    "mining":"minage","validator":"validateur",
    "consensus":"consensus","bridge":"pont",
    "on-chain":"on-chain","off-chain":"off-chain",
    "scam":"arnaque","phishing":"hameçonnage",
    "Learn & Earn":"Apprendre et Gagner",
    "start learning":"commencer à apprendre",
    "checklist":"liste de contrôle","step-by-step":"étape par étape",
    "beginner":"débutant","beginners":"débutants",
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","DEX":"DEX","CEX":"CEX","DApp":"DApp",
    "Layer 1":"Layer 1","Layer 2":"Layer 2",
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    "Evolution of the Web from 1.0 to 3.0":"Évolution du Web de 1.0 à 3.0",
    "Static read-only web pages":"Pages web statiques en lecture seule",
    "Information-centric and interactive":"Centré sur l'information et interactif",
    "User-centric, decentralized, private and secure":"Centré sur l'utilisateur, décentralisé, privé et sécurisé",
    "read-only":"lecture seule","user-centric":"centré utilisateur"
  },
  de: {
    "APR":"Eff. Jahreszins","Annual Percentage Rate":"Effektiver Jahreszins",
    "interest rate":"Zinssatz","annual returns":"Jahresrendite",
    "monthly payouts":"monatliche Auszahlungen","monthly payments":"monatliche Zahlungen",
    "balance":"Kontostand","statement":"Kontoauszug","account":"Konto",
    "deposit":"Einzahlung","withdrawal":"Auszahlung","wire transfer":"Banküberweisung",
    "transaction":"Transaktion","payment":"Zahlung","invoice":"Rechnung",
    "fee":"Gebühr","no hidden fees":"keine versteckten Gebühren",
    "P2P lending":"P2P-Kreditvergabe","crowdlending":"Crowdlending",
    "crowdfunding":"Crowdfunding","lending platform":"Kreditplattform",
    "investment platform":"Investitionsplattform",
    "investor":"Investor","investors":"Investoren",
    "borrower":"Kreditnehmer","lender":"Kreditgeber",
    "loan":"Kredit","loan period":"Kreditlaufzeit","loan term":"Kreditlaufzeit",
    "loan originator":"Kreditanbahner",
    "funded":"finanziert","repaid":"zurückgezahlt",
    "default":"Ausfall","late loans":"verspätete Kredite",
    "cash drag":"Kapitalverzögerung",
    "primary market":"Primärmarkt","secondary market":"Sekundärmarkt",
    "total funded":"Gesamtfinanzierung","total interest paid":"Gesamtzinsen gezahlt",
    "available funds":"verfügbare Mittel","invested funds":"investierte Mittel",
    "total funds":"Gesamtmittel",
    "initial investment":"Erstinvestition","investment period":"Investitionszeitraum",
    "future value":"Endwert","earned return":"erzielter Ertrag",
    "average annual return":"durchschnittliche Jahresrendite",
    "portfolio":"Portfolio","passive income":"passives Einkommen",
    "principal repayment":"Kapitalrückzahlung",
    "interest payment":"Zinszahlung",
    "installment":"Rate","recurring payment":"Dauerauftrag",
    "due diligence":"Sorgfaltsprüfung","risk assessment":"Risikobewertung",
    "risk scoring":"Risikobewertung","AML":"GwG",
    "compliance":"Compliance","regulated":"reguliert",
    "verification":"Verifizierung","KYC":"KYC",
    "referral bonus":"Empfehlungsbonus","loyalty bonus":"Treuebonus",
    "welcome bonus":"Willkommensbonus","investment reward":"Investitionsprämie",
    "invite friends":"Freunde einladen",
    "sign up":"registrieren","log in":"anmelden","register":"registrieren",
    "invest now":"jetzt investieren","start investing":"jetzt anlegen",
    "dashboard":"Dashboard","onboarding":"Kontoeröffnung",
    "collateral":"Sicherheit","mortgage":"Hypothek","savings":"Ersparnisse",
    "credit score":"Bonitätsbewertung","overdraft":"Überziehung",
    "chargeback":"Rückbuchung","settlement":"Abrechnung",
    "direct debit":"Lastschrift","exchange rate":"Wechselkurs",
    "payee":"Zahlungsempfänger","payer":"Zahler","beneficiary":"Begünstigter",
    "equity":"Eigenkapital","liability":"Verbindlichkeit","asset":"Vermögenswert",
    "dividend":"Dividende","spending limit":"Ausgabenlimit",
    "blockchain":"Blockchain","token":"Token","tokens":"Token",
    "stablecoin":"Stablecoin","stablecoins":"Stablecoins",
    "cryptocurrency":"Kryptowährung","crypto":"Krypto",
    "crypto wallet":"Krypto-Wallet","wallet":"Wallet",
    "seed phrase":"Seed-Phrase","private key":"privater Schlüssel",
    "public address":"öffentliche Adresse","smart contract":"Smart Contract",
    "network fees":"Netzwerkgebühren","gas fees":"Gas-Gebühren",
    "custodial":"verwahrt","non-custodial":"nicht-verwahrt",
    "custodial wallet":"verwahrtes Wallet",
    "non-custodial wallet":"nicht-verwahrtes Wallet",
    "fiat":"Fiatgeld","pegged":"gebunden",
    "decentralized":"dezentralisiert","centralized":"zentralisiert",
    "capital provider":"Kapitalgeber",
    "repayment schedule":"Tilgungsplan",
    "leverage":"Hebelwirkung","diversification":"Diversifizierung",
    "yield":"Rendite","returns":"Erträge",
    "liquidity":"Liquidität","protocol":"Protokoll",
    "staking":"Staking","airdrop":"Airdrop",
    "mining":"Mining","validator":"Validator",
    "consensus":"Konsens","bridge":"Bridge",
    "on-chain":"On-Chain","off-chain":"Off-Chain",
    "scam":"Betrug","phishing":"Phishing",
    "Learn & Earn":"Lernen und Verdienen",
    "start learning":"jetzt lernen",
    "checklist":"Checkliste","step-by-step":"Schritt für Schritt",
    "beginner":"Anfänger","beginners":"Anfänger",
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","DEX":"DEX","CEX":"CEX","DApp":"DApp",
    "Layer 1":"Layer 1","Layer 2":"Layer 2",
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    "Evolution of the Web from 1.0 to 3.0":"Entwicklung des Webs von 1.0 bis 3.0",
    "Static read-only web pages":"Statische, schreibgeschützte Webseiten",
    "Information-centric and interactive":"Informationszentriert und interaktiv",
    "User-centric, decentralized, private and secure":"Nutzerzentriert, dezentral, privat und sicher",
    "read-only":"schreibgeschützt","user-centric":"nutzerzentriert"
  },
  pt: {
    "APR":"TAEG","Annual Percentage Rate":"Taxa Anual Efetiva Global",
    "interest rate":"taxa de juro","annual returns":"rendimento anual",
    "monthly payouts":"pagamentos mensais","monthly payments":"pagamentos mensais",
    "balance":"saldo","statement":"extrato","account":"conta",
    "deposit":"depósito","withdrawal":"levantamento","wire transfer":"transferência bancária",
    "transaction":"transação","payment":"pagamento","invoice":"fatura",
    "fee":"comissão","no hidden fees":"sem taxas ocultas",
    "P2P lending":"empréstimos P2P","crowdlending":"crowdlending",
    "crowdfunding":"financiamento coletivo","lending platform":"plataforma de empréstimos",
    "investment platform":"plataforma de investimento",
    "investor":"investidor","investors":"investidores",
    "borrower":"mutuário","lender":"mutuante",
    "loan":"empréstimo","loan period":"prazo do empréstimo","loan term":"prazo do empréstimo",
    "loan originator":"originador de empréstimos",
    "funded":"financiado","repaid":"reembolsado",
    "default":"incumprimento","late loans":"empréstimos em atraso",
    "cash drag":"capital inativo",
    "primary market":"mercado primário","secondary market":"mercado secundário",
    "total funded":"total financiado","total interest paid":"total de juros pagos",
    "available funds":"fundos disponíveis","invested funds":"fundos investidos",
    "total funds":"fundos totais",
    "initial investment":"investimento inicial","investment period":"período de investimento",
    "future value":"valor futuro","earned return":"rendimento obtido",
    "average annual return":"rendimento anual médio",
    "portfolio":"carteira","passive income":"rendimento passivo",
    "principal repayment":"reembolso do capital",
    "interest payment":"pagamento de juros",
    "installment":"prestação","recurring payment":"pagamento recorrente",
    "due diligence":"auditoria prévia","risk assessment":"avaliação de risco",
    "risk scoring":"pontuação de risco","AML":"ABC",
    "compliance":"conformidade regulamentar","regulated":"regulamentado",
    "verification":"verificação","KYC":"KYC",
    "referral bonus":"bónus de referência","loyalty bonus":"bónus de fidelidade",
    "welcome bonus":"bónus de boas-vindas","investment reward":"recompensa de investimento",
    "invite friends":"convidar amigos",
    "sign up":"registar","log in":"iniciar sessão","register":"registar",
    "invest now":"investir agora","start investing":"começar a investir",
    "dashboard":"painel de controlo","onboarding":"registo de cliente",
    "collateral":"garantia","mortgage":"hipoteca","savings":"poupanças",
    "credit score":"pontuação de crédito","overdraft":"descoberto",
    "chargeback":"estorno","settlement":"liquidação",
    "direct debit":"débito direto","exchange rate":"taxa de câmbio",
    "payee":"beneficiário","payer":"pagador","beneficiary":"beneficiário",
    "equity":"capital próprio","liability":"passivo","asset":"ativo",
    "dividend":"dividendo","spending limit":"limite de gastos",
    "blockchain":"blockchain","token":"token","tokens":"tokens",
    "stablecoin":"stablecoin","stablecoins":"stablecoins",
    "cryptocurrency":"criptomoeda","crypto":"cripto",
    "crypto wallet":"carteira cripto","wallet":"carteira",
    "seed phrase":"frase-semente","private key":"chave privada",
    "public address":"endereço público","smart contract":"contrato inteligente",
    "network fees":"taxas de rede","gas fees":"taxas de gas",
    "custodial":"custodial","non-custodial":"não custodial",
    "custodial wallet":"carteira custodial",
    "non-custodial wallet":"carteira não custodial",
    "fiat":"moeda fiduciária","pegged":"indexado",
    "decentralized":"descentralizado","centralized":"centralizado",
    "capital provider":"provedor de capital",
    "repayment schedule":"calendário de reembolso",
    "leverage":"alavancagem","diversification":"diversificação",
    "yield":"rendimento","returns":"rendimentos",
    "liquidity":"liquidez","protocol":"protocolo",
    "staking":"staking","airdrop":"airdrop",
    "mining":"mineração","validator":"validador",
    "consensus":"consenso","bridge":"ponte",
    "on-chain":"on-chain","off-chain":"off-chain",
    "scam":"fraude","phishing":"phishing",
    "Learn & Earn":"Aprender e Ganhar",
    "start learning":"começar a aprender",
    "checklist":"lista de verificação","step-by-step":"passo a passo",
    "beginner":"iniciante","beginners":"iniciantes",
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","DEX":"DEX","CEX":"CEX","DApp":"DApp",
    "Layer 1":"Layer 1","Layer 2":"Layer 2",
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    "Evolution of the Web from 1.0 to 3.0":"Evolução da Web de 1.0 a 3.0",
    "Static read-only web pages":"Páginas web estáticas somente leitura",
    "Information-centric and interactive":"Centrada na informação e interativa",
    "User-centric, decentralized, private and secure":"Centrada no usuário, descentralizada, privada e segura",
    "read-only":"somente leitura","user-centric":"centrada no usuário"
  },
  "pt-br": {
    // Core finance — Brazilian banking vocabulary (saque, parcela, tarifa…)
    "APR":"Taxa Anual","Annual Percentage Rate":"Taxa Percentual Anual",
    "interest rate":"taxa de juros","annual returns":"retornos anuais",
    "monthly payouts":"pagamentos mensais","monthly payments":"pagamentos mensais",
    "balance":"saldo","statement":"extrato","account":"conta",
    "deposit":"depósito","withdrawal":"saque","wire transfer":"transferência bancária",
    "transaction":"transação","payment":"pagamento","invoice":"fatura",
    "fee":"tarifa","no hidden fees":"sem tarifas ocultas",
    // P2P / Crowdlending (Maclear)
    "P2P lending":"empréstimos P2P","crowdlending":"crowdlending",
    "crowdfunding":"financiamento coletivo","lending platform":"plataforma de empréstimos",
    "investment platform":"plataforma de investimentos",
    "investor":"investidor","investors":"investidores",
    "borrower":"tomador","lender":"credor",
    "loan":"empréstimo","loan period":"prazo do empréstimo","loan term":"prazo do empréstimo",
    "loan originator":"originador de empréstimos",
    "funded":"financiado","repaid":"quitado",
    "default":"inadimplência","late loans":"empréstimos em atraso",
    "cash drag":"capital parado",
    "primary market":"mercado primário","secondary market":"mercado secundário",
    "total funded":"total financiado","total interest paid":"total de juros pagos",
    "available funds":"fundos disponíveis","invested funds":"fundos investidos",
    "total funds":"fundos totais",
    // Investment
    "initial investment":"investimento inicial","investment period":"período de investimento",
    "future value":"valor futuro","earned return":"retorno obtido",
    "average annual return":"retorno médio anual",
    "portfolio":"carteira","passive income":"renda passiva",
    "principal repayment":"amortização do principal",
    "interest payment":"pagamento de juros",
    "installment":"parcela","recurring payment":"pagamento recorrente",
    // Compliance & process
    "due diligence":"due diligence","risk assessment":"avaliação de risco",
    "risk scoring":"score de risco","AML":"PLD",
    "compliance":"compliance","regulated":"regulado",
    "verification":"verificação","KYC":"KYC",
    // Bonuses & rewards
    "referral bonus":"bônus de indicação","loyalty bonus":"bônus de fidelidade",
    "welcome bonus":"bônus de boas-vindas","investment reward":"recompensa de investimento",
    "invite friends":"convide amigos",
    // UI actions
    "sign up":"cadastre-se","log in":"entrar","register":"cadastrar",
    "invest now":"invista agora","start investing":"comece a investir",
    "dashboard":"painel de controle","onboarding":"cadastro de cliente",
    // General finance
    "collateral":"garantia","mortgage":"hipoteca","savings":"poupança",
    "credit score":"score de crédito","overdraft":"cheque especial",
    "chargeback":"estorno","settlement":"liquidação",
    "direct debit":"débito automático","exchange rate":"taxa de câmbio",
    "payee":"beneficiário","payer":"pagador","beneficiary":"beneficiário",
    "equity":"patrimônio líquido","liability":"passivo","asset":"ativo",
    "dividend":"dividendo","spending limit":"limite de gastos",
    // Crypto / Web3 (Maclear Crypto Course)
    "blockchain":"blockchain","token":"token","tokens":"tokens",
    "stablecoin":"stablecoin","stablecoins":"stablecoins",
    "cryptocurrency":"criptomoeda","crypto":"cripto",
    "crypto wallet":"carteira cripto","wallet":"carteira",
    "seed phrase":"frase-semente","private key":"chave privada",
    "public address":"endereço público","smart contract":"contrato inteligente",
    "network fees":"taxas de rede","gas fees":"taxas de gás",
    "custodial":"custodial","non-custodial":"não custodial",
    "custodial wallet":"carteira custodial",
    "non-custodial wallet":"carteira não custodial",
    "fiat":"moeda fiduciária","pegged":"atrelado",
    "decentralized":"descentralizado","centralized":"centralizado",
    "capital provider":"provedor de capital",
    "repayment schedule":"cronograma de pagamentos",
    "leverage":"alavancagem","diversification":"diversificação",
    "yield":"rendimento","returns":"retornos",
    "liquidity":"liquidez","protocol":"protocolo",
    "staking":"staking","airdrop":"airdrop",
    "mining":"mineração","validator":"validador",
    "consensus":"consenso","bridge":"ponte",
    "on-chain":"on-chain","off-chain":"off-chain",
    "scam":"golpe","phishing":"phishing",
    "Learn & Earn":"Aprenda e Ganhe",
    "start learning":"comece a aprender",
    "checklist":"checklist","step-by-step":"passo a passo",
    "beginner":"iniciante","beginners":"iniciantes",
    // Tech terms — must stay untranslated
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","DEX":"DEX","CEX":"CEX","DApp":"DApp",
    "Layer 1":"Layer 1","Layer 2":"Layer 2",
    // Date/era labels — keep verbatim
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    // Infographic card text — concise translations
    "Evolution of the Web from 1.0 to 3.0":"Evolução da Web de 1.0 a 3.0",
    "Static read-only web pages":"Páginas web estáticas somente leitura",
    "Information-centric and interactive":"Centrada na informação e interativa",
    "User-centric, decentralized, private and secure":"Centrada no usuário, descentralizada, privada e segura",
    "read-only":"somente leitura","user-centric":"centrada no usuário",
    "private and secure":"privada e segura"
  },
  ko: {
    "APR":"연이율","Annual Percentage Rate":"연이율",
    "interest rate":"이자율","annual returns":"연간 수익률",
    "monthly payouts":"월별 지급","monthly payments":"월별 결제",
    "balance":"잔액","statement":"명세서","account":"계정",
    "deposit":"입금","withdrawal":"출금","wire transfer":"계좌이체",
    "transaction":"거래","payment":"결제","invoice":"청구서",
    "fee":"수수료","no hidden fees":"숨겨진 수수료 없음",
    "P2P lending":"P2P 대출","crowdlending":"크라우드 렌딩",
    "crowdfunding":"크라우드 펀딩","lending platform":"대출 플랫폼",
    "investment platform":"투자 플랫폼",
    "investor":"투자자","investors":"투자자",
    "borrower":"차입자","lender":"대출자",
    "loan":"대출","loan period":"대출 기간","loan term":"대출 기간",
    "loan originator":"대출 발행사",
    "funded":"펀딩 완료","repaid":"상환 완료",
    "default":"부실","late loans":"연체 대출",
    "cash drag":"현금 유동성 지연",
    "primary market":"1차 시장","secondary market":"2차 시장",
    "total funded":"총 펀딩액","total interest paid":"지급 이자 합계",
    "available funds":"사용 가능 자금","invested funds":"투자 자금",
    "total funds":"총 자금",
    "initial investment":"초기 투자","investment period":"투자 기간",
    "future value":"미래 가치","earned return":"획득 수익",
    "average annual return":"평균 연간 수익률",
    "portfolio":"포트폴리오","passive income":"패시브 인컴",
    "principal repayment":"원금 상환",
    "interest payment":"이자 지급",
    "installment":"할부","recurring payment":"정기 결제",
    "due diligence":"실사","risk assessment":"리스크 평가",
    "risk scoring":"리스크 점수","AML":"AML",
    "compliance":"컴플라이언스","regulated":"규제 대상",
    "verification":"본인 확인","KYC":"KYC",
    "referral bonus":"추천 보너스","loyalty bonus":"로열티 보너스",
    "welcome bonus":"웰컴 보너스","investment reward":"투자 리워드",
    "invite friends":"친구 초대",
    "sign up":"회원가입","log in":"로그인","register":"회원가입",
    "invest now":"지금 투자하기","start investing":"투자 시작하기",
    "dashboard":"대시보드","onboarding":"온보딩",
    "collateral":"담보","mortgage":"모기지","savings":"저축",
    "credit score":"신용 점수","overdraft":"당좌대월",
    "chargeback":"지급 거절","settlement":"결제",
    "direct debit":"자동이체","exchange rate":"환율",
    "payee":"수취인","payer":"지급인","beneficiary":"수익자",
    "equity":"자본","liability":"부채","asset":"자산",
    "dividend":"배당","spending limit":"지출 한도",
    "minimum investment":"최소 투자금","maximum investment":"최대 투자금","investment amount":"투자 금액",
    "account holder":"예금주","IBAN":"IBAN","processing time":"처리 소요 시간","business days":"영업일",
    "credit rating":"신용 등급","risk grade":"리스크 등급","maturity":"만기","amortization":"상각",
    "early repayment":"조기 상환","monthly interest":"월 이자","accrued interest":"미수 이자",
    "total return":"총 수익","net return":"순수익","gross return":"총수익(세전)",
    "fixed rate":"고정 금리","variable rate":"변동 금리","compound interest":"복리","simple interest":"단리",
    "capital at risk":"원금 손실 위험","past performance":"과거 실적","past performance is not a guarantee of future results":"과거 실적이 미래 수익을 보장하지 않습니다",
    "financial intermediary":"금융 중개업자","payment institution":"결제 기관","electronic money":"전자화폐",
    "digital assets":"디지털 자산","securities":"유가증권","transfer fee":"송금 수수료",
    "available balance":"출금 가능 잔액","wallet balance":"지갑 잔액","reserved balance":"예약 잔액",
    "pending":"대기 중","completed":"완료","failed":"실패","verification pending":"본인 확인 대기",
    "two-factor authentication":"2단계 인증","regulatory":"규제","SME":"중소기업","borrower company":"차입 기업",
    "payment protection":"지급 보호","buyback guarantee":"매입약정","interest accrual":"이자 발생",
    "GDPR":"GDPR","EEA":"EEA","privacy policy":"개인정보 처리방침","terms of service":"이용약관","AML policy":"AML 정책",
    "payout":"지급","payouts":"지급","refund":"환불","top up":"충전","disbursement":"송금",
    "loyalty program":"로열티 프로그램","referral program":"추천 프로그램","welcome offer":"웰컴 혜택",
    "annualized return":"연환산 수익률","internal rate of return":"내부수익률","holding period":"보유 기간",
    "liquidity risk":"유동성 리스크","credit risk":"신용 리스크","market risk":"시장 리스크",
    "collateralized loan":"담보 대출","unsecured loan":"무담보 대출","loan book":"대출 포트폴리오",
    "underwriting":"심사","origination fee":"발행 수수료","servicing":"대출 관리",
    "escrow":"에스크로","settlement date":"결제일","value date":"가치일",
    "KYC verification":"KYC 인증","identity verification":"신원 확인","proof of address":"주소 증명",
    "iban":"IBAN","swift":"SWIFT","remittance":"해외 송금",
    "slippage":"슬리피지","liquidity pool":"유동성 풀","impermanent loss":"비영구적 손실",
    "DEX":"DEX","CEX":"CEX","order book":"호가창","yield farming":"이자 파밍","APY":"APY","TVL":"TVL",
    "blockchain":"블록체인","token":"토큰","tokens":"토큰",
    "stablecoin":"스테이블코인","stablecoins":"스테이블코인",
    "cryptocurrency":"암호화폐","crypto":"크립토",
    "crypto wallet":"크립토 지갑","wallet":"지갑",
    "seed phrase":"시드 구문","private key":"개인 키",
    "public address":"공개 주소","smart contract":"스마트 컨트랙트",
    "network fees":"네트워크 수수료","gas fees":"가스 수수료",
    "custodial":"수탁형","non-custodial":"비수탁형",
    "custodial wallet":"수탁형 지갑",
    "non-custodial wallet":"비수탁형 지갑",
    "fiat":"법정화폐","pegged":"연동",
    "decentralized":"탈중앙화","centralized":"중앙화",
    "capital provider":"자본 공급자",
    "repayment schedule":"상환 일정",
    "leverage":"레버리지","diversification":"분산 투자",
    "yield":"수익률","returns":"수익",
    "liquidity":"유동성","protocol":"프로토콜",
    "staking":"스테이킹","airdrop":"에어드롭",
    "mining":"채굴","validator":"검증자",
    "consensus":"합의","bridge":"브리지",
    "on-chain":"온체인","off-chain":"오프체인",
    "scam":"사기","phishing":"피싱",
    "Learn & Earn":"학습하고 적립하기",
    "start learning":"학습 시작",
    "checklist":"체크리스트","step-by-step":"단계별",
    "beginner":"초보자","beginners":"초보자",
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","Layer 1":"Layer 1","Layer 2":"Layer 2",
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    "Evolution of the Web from 1.0 to 3.0":"웹의 진화: 1.0에서 3.0까지",
    "Static read-only web pages":"정적 읽기 전용 웹 페이지",
    "Information-centric and interactive":"정보 중심의 인터랙티브 웹",
    "User-centric, decentralized, private and secure":"사용자 중심, 탈중앙화, 프라이버시 및 보안",
    "read-only":"읽기 전용","user-centric":"사용자 중심"
  },
  zh: {
    "APR":"年化利率","Annual Percentage Rate":"年化利率",
    "interest rate":"利率","annual returns":"年化收益",
    "monthly payouts":"按月支付","monthly payments":"每月还款",
    "balance":"余额","statement":"对账单","account":"账户",
    "deposit":"充值","withdrawal":"提现","wire transfer":"银行转账",
    "transaction":"交易","payment":"付款","invoice":"发票",
    "fee":"费用","no hidden fees":"无隐藏费用",
    "P2P lending":"P2P 借贷","crowdlending":"众筹借贷",
    "crowdfunding":"众筹","lending platform":"借贷平台",
    "investment platform":"投资平台",
    "investor":"投资者","investors":"投资者",
    "borrower":"借款人","lender":"出借人",
    "loan":"贷款","loan period":"贷款期限","loan term":"贷款期限",
    "loan originator":"贷款发起方",
    "funded":"已融资","repaid":"已偿还",
    "default":"违约","late loans":"逾期贷款",
    "cash drag":"资金闲置",
    "primary market":"一级市场","secondary market":"二级市场",
    "total funded":"总融资额","total interest paid":"已付利息总额",
    "available funds":"可用资金","invested funds":"已投资资金",
    "total funds":"总资金",
    "initial investment":"初始投资","investment period":"投资期限",
    "future value":"未来价值","earned return":"已获得收益",
    "average annual return":"平均年化收益",
    "portfolio":"投资组合","passive income":"被动收入",
    "principal repayment":"本金偿还",
    "interest payment":"利息支付",
    "installment":"分期","recurring payment":"定期付款",
    "due diligence":"尽职调查","risk assessment":"风险评估",
    "risk scoring":"风险评分","AML":"反洗钱",
    "compliance":"合规","regulated":"受监管",
    "verification":"身份验证","KYC":"KYC",
    "referral bonus":"推荐奖励","loyalty bonus":"忠诚度奖励",
    "welcome bonus":"欢迎奖励","investment reward":"投资奖励",
    "invite friends":"邀请好友",
    "sign up":"注册","log in":"登录","register":"注册",
    "invest now":"立即投资","start investing":"开始投资",
    "dashboard":"控制台","onboarding":"开户引导",
    "collateral":"抵押品","mortgage":"按揭","savings":"储蓄",
    "credit score":"信用评分","overdraft":"透支",
    "chargeback":"拒付","settlement":"结算",
    "direct debit":"直接扣款","exchange rate":"汇率",
    "payee":"收款人","payer":"付款人","beneficiary":"受益人",
    "equity":"权益","liability":"负债","asset":"资产",
    "dividend":"股息","spending limit":"消费限额",
    "minimum investment":"最低投资额","maximum investment":"最高投资额","investment amount":"投资金额",
    "account holder":"账户持有人","IBAN":"IBAN","processing time":"处理时间","business days":"工作日",
    "credit rating":"信用评级","risk grade":"风险等级","maturity":"到期","amortization":"摊销",
    "early repayment":"提前还款","monthly interest":"月息","accrued interest":"应计利息",
    "total return":"总回报","net return":"净收益","gross return":"总收益（税前）",
    "fixed rate":"固定利率","variable rate":"浮动利率","compound interest":"复利","simple interest":"单利",
    "capital at risk":"本金风险","past performance":"历史业绩","past performance is not a guarantee of future results":"过往业绩不代表未来表现",
    "financial intermediary":"金融中介","payment institution":"支付机构","electronic money":"电子货币",
    "digital assets":"数字资产","securities":"证券","transfer fee":"转账手续费",
    "available balance":"可用余额","wallet balance":"钱包余额","reserved balance":"冻结余额",
    "pending":"处理中","completed":"已完成","failed":"失败","verification pending":"验证审核中",
    "two-factor authentication":"双因素认证","regulatory":"监管","SME":"中小企业","borrower company":"借款企业",
    "payment protection":"付款保障","buyback guarantee":"回购担保","interest accrual":"利息计提",
    "GDPR":"GDPR","EEA":"欧洲经济区","privacy policy":"隐私政策","terms of service":"服务条款","AML policy":"反洗钱政策",
    "payout":"到账","payouts":"付款","refund":"退款","top up":"充值","disbursement":"放款",
    "loyalty program":"忠诚度计划","referral program":"推荐计划","welcome offer":"新人礼遇",
    "annualized return":"年化收益","internal rate of return":"内部收益率","holding period":"持有期",
    "liquidity risk":"流动性风险","credit risk":"信用风险","market risk":"市场风险",
    "collateralized loan":"抵押贷款","unsecured loan":"信用贷款","loan book":"贷款组合",
    "underwriting":"授信审批","origination fee":"发起费","servicing":"贷后服务",
    "escrow":"托管账户","settlement date":"结算日","value date":"起息日",
    "KYC verification":"KYC 认证","identity verification":"身份验证","proof of address":"地址证明",
    "iban":"IBAN","swift":"SWIFT","remittance":"汇款",
    "slippage":"滑点","liquidity pool":"流动性池","impermanent loss":"无常损失",
    "DEX":"DEX","CEX":"CEX","order book":"订单簿","yield farming":"流动性挖矿","APY":"APY","TVL":"TVL",
    "blockchain":"区块链","token":"代币","tokens":"代币",
    "stablecoin":"稳定币","stablecoins":"稳定币",
    "cryptocurrency":"加密货币","crypto":"加密资产",
    "crypto wallet":"加密钱包","wallet":"钱包",
    "seed phrase":"助记词","private key":"私钥",
    "public address":"公开地址","smart contract":"智能合约",
    "network fees":"网络费用","gas fees":"Gas 费用",
    "custodial":"托管","non-custodial":"非托管",
    "custodial wallet":"托管钱包",
    "non-custodial wallet":"非托管钱包",
    "fiat":"法币","pegged":"锚定",
    "decentralized":"去中心化","centralized":"中心化",
    "capital provider":"资金提供方",
    "repayment schedule":"还款计划",
    "leverage":"杠杆","diversification":"分散投资",
    "yield":"收益","returns":"回报",
    "liquidity":"流动性","protocol":"协议",
    "staking":"质押","airdrop":"空投",
    "mining":"挖矿","validator":"验证节点",
    "consensus":"共识","bridge":"跨链桥",
    "on-chain":"链上","off-chain":"链下",
    "scam":"诈骗","phishing":"钓鱼",
    "Learn & Earn":"学习即赚",
    "start learning":"开始学习",
    "checklist":"清单","step-by-step":"分步",
    "beginner":"初学者","beginners":"初学者",
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","Layer 1":"Layer 1","Layer 2":"Layer 2",
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    "Evolution of the Web from 1.0 to 3.0":"Web的演进：从1.0到3.0",
    "Static read-only web pages":"静态只读网页",
    "Information-centric and interactive":"以信息为中心的交互式网络",
    "User-centric, decentralized, private and secure":"以用户为中心、去中心化、隐私与安全",
    "read-only":"只读","user-centric":"以用户为中心"
  },
  ja: {
    "APR":"年利","Annual Percentage Rate":"年利",
    "interest rate":"金利","annual returns":"年間リターン",
    "monthly payouts":"月次払い出し","monthly payments":"月次支払い",
    "balance":"残高","statement":"明細","account":"口座",
    "deposit":"入金","withdrawal":"出金","wire transfer":"銀行振込",
    "transaction":"取引","payment":"支払い","invoice":"請求書",
    "fee":"手数料","no hidden fees":"隠れた手数料なし",
    "P2P lending":"P2Pレンディング","crowdlending":"クラウドレンディング",
    "crowdfunding":"クラウドファンディング","lending platform":"融資プラットフォーム",
    "investment platform":"投資プラットフォーム",
    "investor":"投資家","investors":"投資家",
    "borrower":"借り手","lender":"貸し手",
    "loan":"融資","loan period":"融資期間","loan term":"融資期間",
    "loan originator":"ローンオリジネーター",
    "funded":"調達済み","repaid":"返済済み",
    "default":"デフォルト","late loans":"延滞ローン",
    "cash drag":"キャッシュドラッグ",
    "primary market":"プライマリーマーケット","secondary market":"セカンダリーマーケット",
    "total funded":"総調達額","total interest paid":"支払利息合計",
    "available funds":"利用可能資金","invested funds":"投資済み資金",
    "total funds":"総資金",
    "initial investment":"初期投資","investment period":"投資期間",
    "future value":"将来価値","earned return":"獲得リターン",
    "average annual return":"平均年間リターン",
    "portfolio":"ポートフォリオ","passive income":"不労所得",
    "principal repayment":"元本返済",
    "interest payment":"利息支払い",
    "installment":"分割払い","recurring payment":"定期支払い",
    "due diligence":"デューデリジェンス","risk assessment":"リスク評価",
    "risk scoring":"リスクスコア","AML":"AML",
    "compliance":"コンプライアンス","regulated":"規制下",
    "verification":"本人確認","KYC":"KYC",
    "referral bonus":"紹介ボーナス","loyalty bonus":"ロイヤルティボーナス",
    "welcome bonus":"ウェルカムボーナス","investment reward":"投資リワード",
    "invite friends":"友達を招待",
    "sign up":"新規登録","log in":"ログイン","register":"登録",
    "invest now":"今すぐ投資","start investing":"投資を始める",
    "dashboard":"ダッシュボード","onboarding":"オンボーディング",
    "collateral":"担保","mortgage":"住宅ローン","savings":"貯蓄",
    "credit score":"信用スコア","overdraft":"当座貸越",
    "chargeback":"チャージバック","settlement":"決済",
    "direct debit":"口座振替","exchange rate":"為替レート",
    "payee":"受取人","payer":"支払人","beneficiary":"受益者",
    "equity":"資本","liability":"負債","asset":"資産",
    "dividend":"配当","spending limit":"支出上限",
    "minimum investment":"最低投資額","maximum investment":"最大投資額","investment amount":"投資金額",
    "account holder":"口座名義人","IBAN":"IBAN","processing time":"処理時間","business days":"営業日",
    "credit rating":"信用格付け","risk grade":"リスクグレード","maturity":"満期","amortization":"償却",
    "early repayment":"早期返済","monthly interest":"月次利子","accrued interest":"未収利息",
    "total return":"総リターン","net return":"純リターン","gross return":"総リターン（税引前）",
    "fixed rate":"固定金利","variable rate":"変動金利","compound interest":"複利","simple interest":"単利",
    "capital at risk":"元本リスク","past performance":"過去の実績","past performance is not a guarantee of future results":"過去の実績は将来の成果を保証するものではありません",
    "financial intermediary":"金融仲介業者","payment institution":"決済事業者","electronic money":"電子マネー",
    "digital assets":"デジタル資産","securities":"有価証券","transfer fee":"振込手数料",
    "available balance":"利用可能残高","wallet balance":"ウォレット残高","reserved balance":"留保残高",
    "pending":"保留中","completed":"完了","failed":"失敗","verification pending":"本人確認待ち",
    "two-factor authentication":"二要素認証","regulatory":"規制","SME":"中小企業","borrower company":"借入企業",
    "payment protection":"支払保護","buyback guarantee":"買取保証","interest accrual":"利息発生",
    "GDPR":"GDPR","EEA":"EEA","privacy policy":"プライバシーポリシー","terms of service":"利用規約","AML policy":"AML方針",
    "payout":"支払い","payouts":"支払い","refund":"返金","top up":"チャージ","disbursement":"送金",
    "loyalty program":"ロイヤルティプログラム","referral program":"紹介プログラム","welcome offer":"ウェルカム特典",
    "annualized return":"年換算リターン","internal rate of return":"内部収益率","holding period":"保有期間",
    "liquidity risk":"流動性リスク","credit risk":"信用リスク","market risk":"市場リスク",
    "collateralized loan":"担保付ローン","unsecured loan":"無担保ローン","loan book":"ローンブック",
    "underwriting":"与信審査","origination fee":"手数料（組成）","servicing":"サービシング",
    "escrow":"エスクロー","settlement date":"決済日","value date":"バリュー日",
    "KYC verification":"KYC認証","identity verification":"本人確認","proof of address":"住所証明",
    "iban":"IBAN","swift":"SWIFT","remittance":"送金",
    "slippage":"スリッページ","liquidity pool":"流動性プール","impermanent loss":"一時的損失",
    "DEX":"DEX","CEX":"CEX","order book":"オーダーブック","yield farming":"イールドファーミング","APY":"APY","TVL":"TVL",
    "blockchain":"ブロックチェーン","token":"トークン","tokens":"トークン",
    "stablecoin":"ステーブルコイン","stablecoins":"ステーブルコイン",
    "cryptocurrency":"暗号資産","crypto":"クリプト",
    "crypto wallet":"暗号資産ウォレット","wallet":"ウォレット",
    "seed phrase":"シードフレーズ","private key":"秘密鍵",
    "public address":"公開アドレス","smart contract":"スマートコントラクト",
    "network fees":"ネットワーク手数料","gas fees":"ガス代",
    "custodial":"カストディアル","non-custodial":"ノンカストディアル",
    "custodial wallet":"カストディアルウォレット",
    "non-custodial wallet":"ノンカストディアルウォレット",
    "fiat":"法定通貨","pegged":"ペッグ",
    "decentralized":"分散型","centralized":"中央集権型",
    "capital provider":"資本提供者",
    "repayment schedule":"返済スケジュール",
    "leverage":"レバレッジ","diversification":"分散投資",
    "yield":"利回り","returns":"リターン",
    "liquidity":"流動性","protocol":"プロトコル",
    "staking":"ステーキング","airdrop":"エアドロップ",
    "mining":"マイニング","validator":"バリデーター",
    "consensus":"コンセンサス","bridge":"ブリッジ",
    "on-chain":"オンチェーン","off-chain":"オフチェーン",
    "scam":"詐欺","phishing":"フィッシング",
    "Learn & Earn":"学んで稼ぐ",
    "start learning":"学習を始める",
    "checklist":"チェックリスト","step-by-step":"ステップバイステップ",
    "beginner":"初心者","beginners":"初心者",
    "Web 1.0":"Web 1.0","Web 2.0":"Web 2.0","Web 3.0":"Web 3.0",
    "DeFi":"DeFi","NFT":"NFT","DAO":"DAO","Layer 1":"Layer 1","Layer 2":"Layer 2",
    "1900s~2000":"1900s~2000","2000s~2020s":"2000s~2020s","2020s~?":"2020s~?",
    "1900s–2000":"1900s–2000","2000s–2020s":"2000s–2020s","2020s–?":"2020s–?",
    "Evolution of the Web from 1.0 to 3.0":"Webの進化：1.0から3.0へ",
    "Static read-only web pages":"静的な読み取り専用ウェブページ",
    "Information-centric and interactive":"情報中心でインタラクティブ",
    "User-centric, decentralized, private and secure":"ユーザー中心・分散型・プライベート・安全",
    "read-only":"読み取り専用","user-centric":"ユーザー中心"
  }
};

export const LANG_NAMES = { es:"Spanish", it:"Italian", fr:"French", de:"German", pt:"European Portuguese", "pt-br":"Brazilian Portuguese", pl:"Polish", el:"Greek", tr:"Turkish", ko:"Korean", zh:"Simplified Chinese", ja:"Japanese" };

export const COURSE_GLOSSARY = {
  es: {
    "tx as a receipt":"tx como comprobante",
    "transaction hash":"hash de transacción",
    "block explorer":"explorador de bloques",
    "network":"red","base network":"red Base",
    "Interface":"Interfaz","website":"sitio web","confirm":"confirmar","execution":"ejecución",
    "tokenomics":"tokenómica",
    "crypto taxes":"impuestos cripto",
    "real yield":"rendimiento real",
    "approval":"aprobación","approvals":"aprobaciones",
    "spending cap":"límite de gasto",
    "allowance":"asignación",
    "revoke approval":"revocar aprobación",
    "wallet connection":"conexión de monedero",
    "normal login":"inicio de sesión normal",
    "clone site":"sitio clonado","fake support":"soporte falso",
    "support staff":"personal de soporte",
    "wrong address":"dirección incorrecta",
    "malicious transaction":"transacción maliciosa",
    "private key leak":"filtración de clave privada",
    "seed phrase leak":"filtración de frase semilla",
    "risk management":"gestión de riesgos",
    "position sizing":"dimensionamiento de posición",
    "term length":"plazo",
    "investor discipline":"disciplina del inversor",
    "capital preservation":"preservación de capital",
    "money management":"gestión del dinero",
    "operational security":"seguridad operativa",
    "self-custody":"autocustodia",
    "price swings":"oscilaciones de precio",
    "quick reset":"reinicio rápido"
  },
  it: {
    "tx as a receipt":"tx come ricevuta","transaction hash":"hash della transazione",
    "block explorer":"explorer blockchain","network":"rete","base network":"rete Base",
    "Interface":"Interfaccia","website":"sito web","confirm":"conferma","execution":"esecuzione",
    "tokenomics":"tokenomics","crypto taxes":"tasse crypto","real yield":"rendimento reale",
    "approval":"approvazione","approvals":"approvazioni","spending cap":"limite di spesa",
    "allowance":"autorizzazione","revoke approval":"revoca approvazione",
    "wallet connection":"connessione wallet","normal login":"accesso normale",
    "clone site":"sito clone","fake support":"supporto falso","support staff":"staff di supporto",
    "wrong address":"indirizzo errato","malicious transaction":"transazione malevola",
    "private key leak":"fuga della chiave privata","seed phrase leak":"fuga della seed phrase",
    "risk management":"gestione del rischio","position sizing":"dimensionamento posizione",
    "term length":"durata","investor discipline":"disciplina dell'investitore",
    "capital preservation":"preservazione del capitale","money management":"gestione del denaro",
    "operational security":"sicurezza operativa","self-custody":"autocustodia",
    "price swings":"oscillazioni di prezzo","quick reset":"reset rapido"
  },
  fr: {
    "tx as a receipt":"tx comme reçu","transaction hash":"hash de transaction",
    "block explorer":"explorateur de blocs","network":"réseau","base network":"réseau Base",
    "Interface":"Interface","website":"site web","confirm":"confirmer","execution":"exécution",
    "tokenomics":"tokenomics","crypto taxes":"fiscalité crypto","real yield":"rendement réel",
    "approval":"approbation","approvals":"approbations","spending cap":"plafond de dépense",
    "allowance":"autorisation","revoke approval":"révoquer l'approbation",
    "wallet connection":"connexion du portefeuille","normal login":"connexion classique",
    "clone site":"site cloné","fake support":"faux support","support staff":"équipe support",
    "wrong address":"mauvaise adresse","malicious transaction":"transaction malveillante",
    "private key leak":"fuite de clé privée","seed phrase leak":"fuite de phrase de récupération",
    "risk management":"gestion des risques","position sizing":"dimensionnement de position",
    "term length":"durée","investor discipline":"discipline de l'investisseur",
    "capital preservation":"préservation du capital","money management":"gestion de l'argent",
    "operational security":"sécurité opérationnelle","self-custody":"auto-garde",
    "price swings":"variations de prix","quick reset":"réinitialisation rapide"
  },
  de: {
    "tx as a receipt":"TX als Beleg","transaction hash":"Transaktions-Hash",
    "block explorer":"Block-Explorer","network":"Netzwerk","base network":"Base-Netzwerk",
    "Interface":"Oberfläche","website":"Website","confirm":"Bestätigen","execution":"Ausführung",
    "tokenomics":"Tokenomics","crypto taxes":"Krypto-Steuern","real yield":"reale Rendite",
    "approval":"Freigabe","approvals":"Freigaben","spending cap":"Ausgabenlimit",
    "allowance":"Berechtigung","revoke approval":"Freigabe widerrufen",
    "wallet connection":"Wallet-Verbindung","normal login":"normale Anmeldung",
    "clone site":"Klonseite","fake support":"falscher Support","support staff":"Support-Team",
    "wrong address":"falsche Adresse","malicious transaction":"bösartige Transaktion",
    "private key leak":"Leak des privaten Schlüssels","seed phrase leak":"Leak der Seed-Phrase",
    "risk management":"Risikomanagement","position sizing":"Positionsgröße",
    "term length":"Laufzeit","investor discipline":"Investor-Disziplin",
    "capital preservation":"Kapitalerhalt","money management":"Geldmanagement",
    "operational security":"operative Sicherheit","self-custody":"Selbstverwahrung",
    "price swings":"Preisschwankungen","quick reset":"Schnell-Reset"
  },
  pt: {
    "tx as a receipt":"tx como comprovativo","transaction hash":"hash da transação",
    "block explorer":"explorador de blocos","network":"rede","base network":"rede Base",
    "Interface":"Interface","website":"site web","confirm":"confirmar","execution":"execução",
    "tokenomics":"tokenomics","crypto taxes":"impostos cripto","real yield":"rendimento real",
    "approval":"aprovação","approvals":"aprovações","spending cap":"limite de gastos",
    "allowance":"permissão","revoke approval":"revogar aprovação",
    "wallet connection":"conexão da carteira","normal login":"login normal",
    "clone site":"site clonado","fake support":"suporte falso","support staff":"equipa de suporte",
    "wrong address":"endereço errado","malicious transaction":"transação maliciosa",
    "private key leak":"vazamento de chave privada","seed phrase leak":"vazamento da frase-semente",
    "risk management":"gestão de risco","position sizing":"dimensionamento da posição",
    "term length":"prazo","investor discipline":"disciplina do investidor",
    "capital preservation":"preservação de capital","money management":"gestão de dinheiro",
    "operational security":"segurança operacional","self-custody":"autocustódia",
    "price swings":"oscilações de preço","quick reset":"reinício rápido"
  },
  "pt-br": {
    "tx as a receipt":"tx como comprovante","transaction hash":"hash da transação",
    "block explorer":"explorador de blocos","network":"rede","base network":"rede Base",
    "Interface":"Interface","website":"site","confirm":"confirmar","execution":"execução",
    "tokenomics":"tokenomics","crypto taxes":"impostos sobre cripto","real yield":"rendimento real",
    "approval":"aprovação","approvals":"aprovações","spending cap":"limite de gastos",
    "allowance":"permissão","revoke approval":"revogar aprovação",
    "wallet connection":"conexão da carteira","normal login":"login comum",
    "clone site":"site clonado","fake support":"suporte falso","support staff":"equipe de suporte",
    "wrong address":"endereço errado","malicious transaction":"transação maliciosa",
    "private key leak":"vazamento de chave privada","seed phrase leak":"vazamento da frase-semente",
    "risk management":"gestão de riscos","position sizing":"dimensionamento de posição",
    "term length":"prazo","investor discipline":"disciplina do investidor",
    "capital preservation":"preservação de capital","money management":"gestão do dinheiro",
    "operational security":"segurança operacional","self-custody":"autocustódia",
    "price swings":"oscilações de preço","quick reset":"reinício rápido"
  },
  ko: {
    "tx as a receipt":"영수증으로서의 tx","transaction hash":"트랜잭션 해시",
    "block explorer":"블록 익스플로러","network":"네트워크","base network":"Base 네트워크",
    "Interface":"인터페이스","website":"웹사이트","confirm":"확인","execution":"실행",
    "tokenomics":"토크노믹스","crypto taxes":"암호화폐 세금","real yield":"실질 수익률",
    "approval":"승인","approvals":"승인","spending cap":"지출 한도",
    "allowance":"허용 한도","revoke approval":"승인 취소",
    "wallet connection":"지갑 연결","normal login":"일반 로그인",
    "clone site":"복제 사이트","fake support":"가짜 지원","support staff":"지원팀",
    "wrong address":"잘못된 주소","malicious transaction":"악성 거래",
    "private key leak":"개인 키 유출","seed phrase leak":"시드 구문 유출",
    "risk management":"리스크 관리","position sizing":"포지션 크기",
    "term length":"기간","investor discipline":"투자자 규율",
    "capital preservation":"자본 보전","money management":"자금 관리",
    "operational security":"운영 보안","self-custody":"셀프 커스터디",
    "price swings":"가격 변동",
    "perpetual contract":"무기한 계약","oracle":"오라클","liquidation":"강제 청산",
    "rug pull":"럭풀","honeypot":"허니팟","smart contract audit":"스마트 컨트랙트 감사",
    "over-collateralization":"과담보","flash loan":"플래시론","MEV":"MEV",
    "quick reset":"빠른 재설정"
  },
  zh: {
    "tx as a receipt":"交易作为凭证","transaction hash":"交易哈希",
    "block explorer":"区块浏览器","network":"网络","base network":"Base 网络",
    "Interface":"界面","website":"网站","confirm":"确认","execution":"执行",
    "tokenomics":"代币经济学","crypto taxes":"加密税务","real yield":"真实收益",
    "approval":"授权","approvals":"授权","spending cap":"支出上限",
    "allowance":"额度","revoke approval":"撤销授权",
    "wallet connection":"钱包连接","normal login":"常规登录",
    "clone site":"克隆网站","fake support":"假冒客服","support staff":"客服人员",
    "wrong address":"错误地址","malicious transaction":"恶意交易",
    "private key leak":"私钥泄露","seed phrase leak":"助记词泄露",
    "risk management":"风险管理","position sizing":"仓位规模",
    "term length":"期限","investor discipline":"投资者纪律",
    "capital preservation":"资本保全","money management":"资金管理",
    "operational security":"运营安全","self-custody":"自托管",
    "price swings":"价格波动",
    "perpetual contract":"永续合约","oracle":"预言机","liquidation":"强制平仓",
    "rug pull":"跑路","honeypot":"蜜罐","smart contract audit":"智能合约审计",
    "over-collateralization":"超额抵押","flash loan":"闪电贷","MEV":"MEV",
    "quick reset":"快速重置"
  },
  ja: {
    "tx as a receipt":"領収書としてのtx","transaction hash":"トランザクションハッシュ",
    "block explorer":"ブロックエクスプローラー","network":"ネットワーク","base network":"Baseネットワーク",
    "Interface":"インターフェース","website":"ウェブサイト","confirm":"確認","execution":"実行",
    "tokenomics":"トークノミクス","crypto taxes":"暗号資産税","real yield":"実質利回り",
    "approval":"承認","approvals":"承認","spending cap":"支出上限",
    "allowance":"許可額","revoke approval":"承認を取り消す",
    "wallet connection":"ウォレット接続","normal login":"通常ログイン",
    "clone site":"クローンサイト","fake support":"偽サポート","support staff":"サポート担当",
    "wrong address":"誤ったアドレス","malicious transaction":"悪意のある取引",
    "private key leak":"秘密鍵の漏洩","seed phrase leak":"シードフレーズの漏洩",
    "risk management":"リスク管理","position sizing":"ポジションサイズ",
    "term length":"期間","investor discipline":"投資家の規律",
    "capital preservation":"資本保全","money management":"資金管理",
    "operational security":"運用セキュリティ","self-custody":"セルフカストディ",
    "price swings":"価格変動",
    "perpetual contract":"無期限契約","oracle":"オラクル","liquidation":"清算",
    "rug pull":"ラグプル","honeypot":"ハニーポット","smart contract audit":"スマートコントラクト監査",
    "over-collateralization":"過剰担保","flash loan":"フラッシュローン","MEV":"MEV",
    "quick reset":"クイックリセット"
  }
};
